Skeleton for git payload
kube-tarian/kad pull request #225
Opened 2023-09-21 15:51 UTC by indresh-28

2023-09-26 17:08 UTC, indresh-28 commented on capten/model/server.gen.go
> +	Token      string `json:"Token,omitempty"`
Don't store the creds, as it stored in the cassandra.
Read from the vault.

2023-09-26 17:13 UTC, indresh-28 commented on capten/model/server.gen.go
> +	PluginName string `json:"PluginName,omitempty"`
USe case, repourl, cred type(read from vault).

2023-09-26 17:15 UTC, indresh-28 commented on capten/config-worker/Dockerfile
> +ENTRYPOINT ["/config_worker"]
placeholder to replace the template configuration.

2023-09-26 17:17 UTC, indresh-28 commented on capten/common-pkg/plugins/git/git.go
> +			Name:  "capten-agent-bot",
Take the env or use default.

2023-09-26 17:18 UTC, indresh-28 commented on capten/common-pkg/plugins/git/git.go
> +		RefSpecs: []config.RefSpec{config.RefSpec("refs/heads/main:refs/heads/" + branchName),
Need confirmation. Add branch name to env.
Automatically create the PR after the push against the default repo branch

2023-09-26 17:22 UTC, indresh-28 commented on capten/config-worker/pkg/activities/git_configure.go
> +	cmd := exec.Command("cp", "--recursive", filepath.Join("./", GitTemplateDir, appDir), dir)
Look for alternative to remove the shell from the docker image. Try to use programmatically

2023-10-03 15:32 UTC, vramk23 requested changes

2023-10-03 15:32 UTC, vramk23 commented on capten/config-worker/Dockerfile
> -
USER need to retained

2023-10-03 15:32 UTC, vramk23 commented on capten/config-worker/Dockerfile
> +COPY --from=builder ./config-worker/git-config-files /git-config-files
rename folder to /gitopts-template

under this folder different usecase to be used.

 /gitopts-templates
   /cicd
   /scm

for tekton use case, folder structure needed to be added under /cicd folder, not single file.

2023-10-08 16:10 UTC, vramk23 approved these changes

2023-10-08 16:10 UTC, merged