delete operation is added
kube-tarian/kad pull request #311
Opened 2023-11-08 19:28 UTC by anil-intelops

2023-11-09 15:54 UTC, vramk23 requested changes

2023-11-09 15:54 UTC, vramk23 commented on capten/agent/pkg/capten-store/tekton_projects.go
> +			}
else block not needed

2023-11-09 15:54 UTC, vramk23 commented on capten/agent/pkg/capten-store/crossplane_project.go
> +		}
else block not needed

2023-11-09 15:54 UTC, vramk23 commented on capten/agent/pkg/capten-store/argocd_projects.go
> +			}
else block not needed

2023-11-09 15:54 UTC, vramk23 commented on capten/agent/pkg/capten-store/argocd_projects.go
>  	ret := make([]*model.ArgoCDProject, 0)
check first if exist in map, if exist use ap project from the map,
if not exist, create and add the project.

do the same for other methosds

project := &model.ArgoCDProject{Id: gitProject.Id, GitProjectId: gitProject.Id,
			GitProjectUrl: gitProject.ProjectUrl}
		if ap, ok := argoCDProjects[gitProject.Id]; !ok {
			project.Status = string(model.ArgoCDProjectAvailable)
			project.LastUpdateTime = time.Now().Format(time.RFC3339)
			if err := a.UpsertArgoCDProject(project); err != nil {
				return nil, err
			}
		} else {
			project.Status = argoCDProjects[gitProject.Id].Status
			project.LastUpdateTime = ap.LastUpdateTime
		}

2023-11-09 15:54 UTC, vramk23 commented on capten/agent/pkg/agent/plugin_git_apis.go
>  	a.log.Infof("Delete Git project %s request recieved", request.Id)
missing vault cred deletion for cloud provider delete api

2023-11-11 05:40 UTC, anil-intelops commented on capten/agent/pkg/capten-store/tekton_projects.go
> +			}
done

2023-11-11 07:00 UTC, merged