Devbranch
kube-tarian/kad pull request #87
Opened 2023-05-14 13:20 UTC by Shifna12Zarnaz

Added PostCredentials in Vault.go and PostStoreCred in handler_storage.go

2023-05-14 15:50 UTC, srikrishnabh1 requested changes

2023-05-14 15:50 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +func (v *Vault) PostCredentials(secretName, username, password, astradbcreds string) error {
you should also write get credential func else how can we get data?

2023-05-14 15:50 UTC, srikrishnabh1 commented on server/pkg/handler/handle_storage.go
> +	var req api.StoreAgentCredRequest
I dont see vault has been called here.

2023-05-14 18:00 UTC, Shifna12Zarnaz commented
Added the get credentials and postcredentials in vault.go and respective handlers

2023-05-15 14:04 UTC, closed without merging

2023-05-18 18:34 UTC, srikrishnabh1 commented on server/pkg/handler/handle_storage.go
> +	astradbcreds := "secretname/astrabdcreds"
dont hardcode this

2023-05-18 18:35 UTC, srikrishnabh1 commented on server/pkg/handler/handle_storage.go
> +// func (a *APIHandler) PostStoreCred(c *gin.Context) {
Why is this commented, we need this to store the credentials in the agent

2023-05-18 18:35 UTC, srikrishnabh1 reviewed
fix the review comments