Added a feature to automate unsealing operation of vault
kube-tarian/kad pull request #90
Opened 2023-05-19 14:00 UTC by Shifna12Zarnaz

Added a file vault2.go under server/pkg/client/vault2.go.It ll generate unseal keys and store that keys in vault and check the status of vault whether it is sealed or not for every 1 min and automatically unseal it if vault is sealed.Tested separately as a package.Also in tha server main.go added the go routine to the monitoring function

2023-05-19 17:09 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +		fmt.Println("Unsealed")
what is the use of this print statement

2023-05-19 17:10 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +	fmt.Println("Client is", client)
what is the use if this print statement

2023-05-19 17:10 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +	_, err := v.client.KVv2(secretName).Put(ctx, astradbcreds, secretData)
post credentials is generic function name, why is it astradb specific names passed

2023-05-19 17:11 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +	//fmt.Println("")
remove dead code

2023-05-19 17:11 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +	log.Println("Secret written successfully.")
Can you make it debug

2023-05-19 17:12 UTC, srikrishnabh1 commented on server/pkg/client/vault.go
> +func (v *Vault) GetCredentials(secretName, astradbcreds string) (string, string, error) {
we should use generic name the variable name is specific to astradb

2023-05-19 17:12 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +package client
Refactor the code and make it modular.

2023-05-19 17:13 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +	if err != nil {
bad practice

2023-05-19 17:13 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +		if err.Error() == "secrets \""+secretName+"\" not found" {
we should not check error like this

2023-05-19 17:15 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +func StartMonitoringService() {
this should be go routine

2023-05-19 17:15 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +		fmt.Println("Error while sealing", err)
improper error message

2023-05-19 17:15 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +		Address: "http://127.0.0.1:8200",
vault address cannot be hardcoded like this

2023-05-19 17:16 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +	vault := Vault{
why don't we use the client directly. Why are we assigning the client to vault?

2023-05-19 17:17 UTC, srikrishnabh1 commented on server/pkg/client/vault2.go
> +		if !status.Initialized {
Status will always be same value until you update.

2023-05-19 17:23 UTC, srikrishnabh1 requested changes
Please fix the review comments

2023-05-19 17:26 UTC, Shifna12Zarnaz commented on server/pkg/client/vault2.go
> +func StartMonitoringService() {
yas....I have called in main

2023-05-20 08:28 UTC, neha01 requested changes

2023-05-20 12:48 UTC, Shifna12Zarnaz commented on server/cmd/server/main.go
> +	"github.com/kube-tarian/kad/server/pkg/client"
sry am not getting you

2023-05-20 12:52 UTC, Shifna12Zarnaz commented
Added vault2.go

2023-05-20 12:53 UTC, Shifna12Zarnaz commented
Added vault2.go with specified changes

2023-05-20 12:56 UTC, neha01 commented on server/cmd/server/main.go
> +	"github.com/kube-tarian/kad/server/pkg/client"
when you goimport file you group native go modules and third party modules separately.
https://pkg.go.dev/golang.org/x/tools/cmd/goimports
Medium article: https://rgalus.medium.com/how-to-format-your-go-projects-with-gofmt-goimports-and-git-d1fa3c3723ac

2023-07-09 10:29 UTC, vramk23 commented
not needed

2023-07-09 10:29 UTC, closed without merging